spring.application.name=trefelt
spring.datasource.initialization-mode=always
spring.datasource.url=jdbc:mysql://localhost:3306/trefelt_pedidos
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
